/**
 * This class is generated by jOOQ
 */
package models.public_;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1911230325;

	/**
	 * The singleton instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			models.public_.Sequences.SYSTEM_SEQUENCE_1DE3C2E8_320D_45E0_A1FB_96E582DD9B2E,
			models.public_.Sequences.SYSTEM_SEQUENCE_71A24E8D_F79B_4765_8692_6DB4662CC3BD,
			models.public_.Sequences.SYSTEM_SEQUENCE_80306ECB_1C25_402A_938E_6537830F2028,
			models.public_.Sequences.SYSTEM_SEQUENCE_8AD008FB_D000_498A_9DF5_A1C66B7F102F,
			models.public_.Sequences.SYSTEM_SEQUENCE_9E206EF9_BFDD_477C_A431_77ACA5A2184C,
			models.public_.Sequences.SYSTEM_SEQUENCE_E68A78A2_FFF6_40C8_81FA_8677368D98D2);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			models.public_.tables.Meeting.MEETING,
			models.public_.tables.User.USER,
			models.public_.tables.Meetinguser.MEETINGUSER,
			models.public_.tables.File.FILE,
			models.public_.tables.Typefile.TYPEFILE,
			models.public_.tables.Comment.COMMENT);
	}
}
