/**
 * This class is generated by jOOQ
 */
package models.public_;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1342209725;

	/**
	 * The singleton instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			models.public_.Sequences.SYSTEM_SEQUENCE_22CDDEDC_C572_490D_A568_C631635AAFED,
			models.public_.Sequences.SYSTEM_SEQUENCE_33BE06EC_8C45_469F_A39F_F6147C45E373,
			models.public_.Sequences.SYSTEM_SEQUENCE_5166BB2C_82CA_4C30_B4A2_1D6DC2249B51,
			models.public_.Sequences.SYSTEM_SEQUENCE_7F0CD5EE_5ED0_4175_95C4_1BDE1E9FE3AB,
			models.public_.Sequences.SYSTEM_SEQUENCE_E11705A8_5B93_46F5_AEB8_03246C43F56A,
			models.public_.Sequences.SYSTEM_SEQUENCE_E99B3CD4_3586_4862_A2BE_B8990191BC5F);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			models.public_.tables.Meeting.MEETING,
			models.public_.tables.User.USER,
			models.public_.tables.Meetinguser.MEETINGUSER,
			models.public_.tables.File.FILE,
			models.public_.tables.Typefile.TYPEFILE,
			models.public_.tables.Comment.COMMENT);
	}
}
