/**
 * This class is generated by jOOQ
 */
package models.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1DE3C2E8_320D_45E0_A1FB_96E582DD9B2E</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_1DE3C2E8_320D_45E0_A1FB_96E582DD9B2E = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_1DE3C2E8_320D_45E0_A1FB_96E582DD9B2E", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_71A24E8D_F79B_4765_8692_6DB4662CC3BD</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_71A24E8D_F79B_4765_8692_6DB4662CC3BD = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_71A24E8D_F79B_4765_8692_6DB4662CC3BD", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_80306ECB_1C25_402A_938E_6537830F2028</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_80306ECB_1C25_402A_938E_6537830F2028 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_80306ECB_1C25_402A_938E_6537830F2028", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_8AD008FB_D000_498A_9DF5_A1C66B7F102F</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_8AD008FB_D000_498A_9DF5_A1C66B7F102F = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_8AD008FB_D000_498A_9DF5_A1C66B7F102F", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_9E206EF9_BFDD_477C_A431_77ACA5A2184C</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_9E206EF9_BFDD_477C_A431_77ACA5A2184C = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_9E206EF9_BFDD_477C_A431_77ACA5A2184C", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_E68A78A2_FFF6_40C8_81FA_8677368D98D2</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_E68A78A2_FFF6_40C8_81FA_8677368D98D2 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_E68A78A2_FFF6_40C8_81FA_8677368D98D2", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
