/**
 * This class is generated by jOOQ
 */
package models.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_22CDDEDC_C572_490D_A568_C631635AAFED</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_22CDDEDC_C572_490D_A568_C631635AAFED = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_22CDDEDC_C572_490D_A568_C631635AAFED", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_33BE06EC_8C45_469F_A39F_F6147C45E373</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_33BE06EC_8C45_469F_A39F_F6147C45E373 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_33BE06EC_8C45_469F_A39F_F6147C45E373", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_5166BB2C_82CA_4C30_B4A2_1D6DC2249B51</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_5166BB2C_82CA_4C30_B4A2_1D6DC2249B51 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_5166BB2C_82CA_4C30_B4A2_1D6DC2249B51", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_7F0CD5EE_5ED0_4175_95C4_1BDE1E9FE3AB</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_7F0CD5EE_5ED0_4175_95C4_1BDE1E9FE3AB = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_7F0CD5EE_5ED0_4175_95C4_1BDE1E9FE3AB", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_E11705A8_5B93_46F5_AEB8_03246C43F56A</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_E11705A8_5B93_46F5_AEB8_03246C43F56A = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_E11705A8_5B93_46F5_AEB8_03246C43F56A", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_E99B3CD4_3586_4862_A2BE_B8990191BC5F</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_E99B3CD4_3586_4862_A2BE_B8990191BC5F = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_E99B3CD4_3586_4862_A2BE_B8990191BC5F", models.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
