/**
 * This class is generated by jOOQ
 */
package models.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.MEETING
	 */
	public static final models.public_.tables.Meeting MEETING = models.public_.tables.Meeting.MEETING;

	/**
	 * The table PUBLIC.USER
	 */
	public static final models.public_.tables.User USER = models.public_.tables.User.USER;

	/**
	 * The table PUBLIC.MEETINGUSER
	 */
	public static final models.public_.tables.Meetinguser MEETINGUSER = models.public_.tables.Meetinguser.MEETINGUSER;

	/**
	 * The table PUBLIC.FILE
	 */
	public static final models.public_.tables.File FILE = models.public_.tables.File.FILE;

	/**
	 * The table PUBLIC.TYPEFILE
	 */
	public static final models.public_.tables.Typefile TYPEFILE = models.public_.tables.Typefile.TYPEFILE;

	/**
	 * The table PUBLIC.COMMENT
	 */
	public static final models.public_.tables.Comment COMMENT = models.public_.tables.Comment.COMMENT;
}
