/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<models.tables.records.CommentRecord> PK_COMMENT = UniqueKeys0.PK_COMMENT;
	public static final org.jooq.UniqueKey<models.tables.records.FileRecord> PK_FILE = UniqueKeys0.PK_FILE;
	public static final org.jooq.UniqueKey<models.tables.records.MeetingRecord> PK_MEETING = UniqueKeys0.PK_MEETING;
	public static final org.jooq.UniqueKey<models.tables.records.MeetinguserRecord> PK_MEETINGUSER = UniqueKeys0.PK_MEETINGUSER;
	public static final org.jooq.UniqueKey<models.tables.records.SessionRecord> PK_SESSION = UniqueKeys0.PK_SESSION;
	public static final org.jooq.UniqueKey<models.tables.records.UserRecord> PK_USER = UniqueKeys0.PK_USER;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<models.tables.records.CommentRecord> PK_COMMENT = createUniqueKey(models.tables.Comment.COMMENT, models.tables.Comment.COMMENT.ID);
		public static final org.jooq.UniqueKey<models.tables.records.FileRecord> PK_FILE = createUniqueKey(models.tables.File.FILE, models.tables.File.FILE.ID);
		public static final org.jooq.UniqueKey<models.tables.records.MeetingRecord> PK_MEETING = createUniqueKey(models.tables.Meeting.MEETING, models.tables.Meeting.MEETING.ID);
		public static final org.jooq.UniqueKey<models.tables.records.MeetinguserRecord> PK_MEETINGUSER = createUniqueKey(models.tables.Meetinguser.MEETINGUSER, models.tables.Meetinguser.MEETINGUSER.ID);
		public static final org.jooq.UniqueKey<models.tables.records.SessionRecord> PK_SESSION = createUniqueKey(models.tables.Session.SESSION, models.tables.Session.SESSION.ID);
		public static final org.jooq.UniqueKey<models.tables.records.UserRecord> PK_USER = createUniqueKey(models.tables.User.USER, models.tables.User.USER.LOGIN);
	}
}
