/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Comment
	 */
	public static final models.tables.Comment COMMENT = models.tables.Comment.COMMENT;

	/**
	 * The table File
	 */
	public static final models.tables.File FILE = models.tables.File.FILE;

	/**
	 * The table Meeting
	 */
	public static final models.tables.Meeting MEETING = models.tables.Meeting.MEETING;

	/**
	 * The table MeetingUser
	 */
	public static final models.tables.Meetinguser MEETINGUSER = models.tables.Meetinguser.MEETINGUSER;

	/**
	 * The table Session
	 */
	public static final models.tables.Session SESSION = models.tables.Session.SESSION;

	/**
	 * The table User
	 */
	public static final models.tables.User USER = models.tables.User.USER;

	/**
	 * The table sqlite_sequence
	 */
	public static final models.tables.SqliteSequence SQLITE_SEQUENCE = models.tables.SqliteSequence.SQLITE_SEQUENCE;
}
