/**
 * This class is generated by jOOQ
 */
package models.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meetinguser extends org.jooq.impl.TableImpl<models.public_.tables.records.MeetinguserRecord> {

	private static final long serialVersionUID = 1610040922;

	/**
	 * The singleton instance of <code>PUBLIC.MEETINGUSER</code>
	 */
	public static final models.public_.tables.Meetinguser MEETINGUSER = new models.public_.tables.Meetinguser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.public_.tables.records.MeetinguserRecord> getRecordType() {
		return models.public_.tables.records.MeetinguserRecord.class;
	}

	/**
	 * The column <code>PUBLIC.MEETINGUSER.ID</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.MeetinguserRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>PUBLIC.MEETINGUSER.MEETINGID</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.MeetinguserRecord, java.lang.Integer> MEETINGID = createField("MEETINGID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>PUBLIC.MEETINGUSER.USERID</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.MeetinguserRecord, java.lang.Integer> USERID = createField("USERID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>PUBLIC.MEETINGUSER.JOINTIME</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.MeetinguserRecord, java.sql.Timestamp> JOINTIME = createField("JOINTIME", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>PUBLIC.MEETINGUSER</code> table reference
	 */
	public Meetinguser() {
		super("MEETINGUSER", models.public_.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.MEETINGUSER</code> table reference
	 */
	public Meetinguser(java.lang.String alias) {
		super(alias, models.public_.Public.PUBLIC, models.public_.tables.Meetinguser.MEETINGUSER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<models.public_.tables.records.MeetinguserRecord, java.lang.Integer> getIdentity() {
		return models.public_.Keys.IDENTITY_MEETINGUSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.public_.tables.records.MeetinguserRecord> getPrimaryKey() {
		return models.public_.Keys.CONSTRAINT_4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.public_.tables.records.MeetinguserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.public_.tables.records.MeetinguserRecord>>asList(models.public_.Keys.CONSTRAINT_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.public_.tables.Meetinguser as(java.lang.String alias) {
		return new models.public_.tables.Meetinguser(alias);
	}
}
