/**
 * This class is generated by jOOQ
 */
package models.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Typefile extends org.jooq.impl.TableImpl<models.public_.tables.records.TypefileRecord> {

	private static final long serialVersionUID = 801306123;

	/**
	 * The singleton instance of <code>PUBLIC.TYPEFILE</code>
	 */
	public static final models.public_.tables.Typefile TYPEFILE = new models.public_.tables.Typefile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.public_.tables.records.TypefileRecord> getRecordType() {
		return models.public_.tables.records.TypefileRecord.class;
	}

	/**
	 * The column <code>PUBLIC.TYPEFILE.ID</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.TypefileRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>PUBLIC.TYPEFILE.NAME</code>. 
	 */
	public final org.jooq.TableField<models.public_.tables.records.TypefileRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>PUBLIC.TYPEFILE</code> table reference
	 */
	public Typefile() {
		super("TYPEFILE", models.public_.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.TYPEFILE</code> table reference
	 */
	public Typefile(java.lang.String alias) {
		super(alias, models.public_.Public.PUBLIC, models.public_.tables.Typefile.TYPEFILE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<models.public_.tables.records.TypefileRecord, java.lang.Integer> getIdentity() {
		return models.public_.Keys.IDENTITY_TYPEFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.public_.tables.records.TypefileRecord> getPrimaryKey() {
		return models.public_.Keys.CONSTRAINT_65;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.public_.tables.records.TypefileRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.public_.tables.records.TypefileRecord>>asList(models.public_.Keys.CONSTRAINT_65);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.public_.tables.Typefile as(java.lang.String alias) {
		return new models.public_.tables.Typefile(alias);
	}
}
