/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment extends org.jooq.impl.TableImpl<models.tables.records.CommentRecord> {

	private static final long serialVersionUID = -333296038;

	/**
	 * The singleton instance of <code>Comment</code>
	 */
	public static final models.tables.Comment COMMENT = new models.tables.Comment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.CommentRecord> getRecordType() {
		return models.tables.records.CommentRecord.class;
	}

	/**
	 * The column <code>Comment.id</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.CommentRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>Comment.fileId</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.CommentRecord, java.lang.Integer> FILEID = createField("fileId", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>Comment.userLogin</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.CommentRecord, java.lang.String> USERLOGIN = createField("userLogin", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>Comment.date</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.CommentRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>Comment.content</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.CommentRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>Comment</code> table reference
	 */
	public Comment() {
		super("Comment", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>Comment</code> table reference
	 */
	public Comment(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.Comment.COMMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.CommentRecord> getPrimaryKey() {
		return models.Keys.PK_COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.CommentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.CommentRecord>>asList(models.Keys.PK_COMMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.Comment as(java.lang.String alias) {
		return new models.tables.Comment(alias);
	}
}
