/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File extends org.jooq.impl.TableImpl<models.tables.records.FileRecord> {

	private static final long serialVersionUID = 795873533;

	/**
	 * The singleton instance of <code>File</code>
	 */
	public static final models.tables.File FILE = new models.tables.File();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.FileRecord> getRecordType() {
		return models.tables.records.FileRecord.class;
	}

	/**
	 * The column <code>File.id</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>File.meetingUserId</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.lang.Integer> MEETINGUSERID = createField("meetingUserId", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>File.name</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>File.sizeKb</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.lang.Integer> SIZEKB = createField("sizeKb", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>File.addedTime</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.sql.Timestamp> ADDEDTIME = createField("addedTime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>File.hashMD5</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.FileRecord, java.lang.String> HASHMD5 = createField("hashMD5", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>File</code> table reference
	 */
	public File() {
		super("File", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>File</code> table reference
	 */
	public File(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.File.FILE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.FileRecord> getPrimaryKey() {
		return models.Keys.PK_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.FileRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.FileRecord>>asList(models.Keys.PK_FILE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.File as(java.lang.String alias) {
		return new models.tables.File(alias);
	}
}
