/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meetinguser extends org.jooq.impl.TableImpl<models.tables.records.MeetinguserRecord> {

	private static final long serialVersionUID = 1690116450;

	/**
	 * The singleton instance of <code>MeetingUser</code>
	 */
	public static final models.tables.Meetinguser MEETINGUSER = new models.tables.Meetinguser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.MeetinguserRecord> getRecordType() {
		return models.tables.records.MeetinguserRecord.class;
	}

	/**
	 * The column <code>MeetingUser.id</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.MeetinguserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MeetingUser.meetingId</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.MeetinguserRecord, java.lang.Integer> MEETINGID = createField("meetingId", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MeetingUser.userLogin</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.MeetinguserRecord, java.lang.String> USERLOGIN = createField("userLogin", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>MeetingUser.joinTime</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.MeetinguserRecord, java.sql.Timestamp> JOINTIME = createField("joinTime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>MeetingUser</code> table reference
	 */
	public Meetinguser() {
		super("MeetingUser", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>MeetingUser</code> table reference
	 */
	public Meetinguser(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.Meetinguser.MEETINGUSER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.MeetinguserRecord> getPrimaryKey() {
		return models.Keys.PK_MEETINGUSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.MeetinguserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.MeetinguserRecord>>asList(models.Keys.PK_MEETINGUSER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.Meetinguser as(java.lang.String alias) {
		return new models.tables.Meetinguser(alias);
	}
}
