/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Session extends org.jooq.impl.TableImpl<models.tables.records.SessionRecord> {

	private static final long serialVersionUID = -1073289754;

	/**
	 * The singleton instance of <code>Session</code>
	 */
	public static final models.tables.Session SESSION = new models.tables.Session();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.SessionRecord> getRecordType() {
		return models.tables.records.SessionRecord.class;
	}

	/**
	 * The column <code>Session.id</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.SessionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>Session.userLogin</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.SessionRecord, java.lang.String> USERLOGIN = createField("userLogin", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>Session.sid</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.SessionRecord, java.lang.String> SID = createField("sid", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>Session</code> table reference
	 */
	public Session() {
		super("Session", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>Session</code> table reference
	 */
	public Session(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.Session.SESSION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.SessionRecord> getPrimaryKey() {
		return models.Keys.PK_SESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.SessionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.SessionRecord>>asList(models.Keys.PK_SESSION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.Session as(java.lang.String alias) {
		return new models.tables.Session(alias);
	}
}
