/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence extends org.jooq.impl.TableImpl<models.tables.records.SqliteSequenceRecord> {

	private static final long serialVersionUID = -1732550991;

	/**
	 * The singleton instance of <code>sqlite_sequence</code>
	 */
	public static final models.tables.SqliteSequence SQLITE_SEQUENCE = new models.tables.SqliteSequence();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.SqliteSequenceRecord> getRecordType() {
		return models.tables.records.SqliteSequenceRecord.class;
	}

	/**
	 * The column <code>sqlite_sequence.name</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.SqliteSequenceRecord, java.lang.Object> NAME = createField("name", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this);

	/**
	 * The column <code>sqlite_sequence.seq</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.SqliteSequenceRecord, java.lang.Object> SEQ = createField("seq", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this);

	/**
	 * Create a <code>sqlite_sequence</code> table reference
	 */
	public SqliteSequence() {
		super("sqlite_sequence", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>sqlite_sequence</code> table reference
	 */
	public SqliteSequence(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.SqliteSequence.SQLITE_SEQUENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.SqliteSequence as(java.lang.String alias) {
		return new models.tables.SqliteSequence(alias);
	}
}
