/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<models.tables.records.UserRecord> {

	private static final long serialVersionUID = -733745392;

	/**
	 * The singleton instance of <code>User</code>
	 */
	public static final models.tables.User USER = new models.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.UserRecord> getRecordType() {
		return models.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>User.login</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.UserRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>User.name</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.UserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>User.email</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.UserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>User.password</code>. 
	 */
	public final org.jooq.TableField<models.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>User</code> table reference
	 */
	public User() {
		super("User", models.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>User</code> table reference
	 */
	public User(java.lang.String alias) {
		super(alias, models.DefaultSchema.DEFAULT_SCHEMA, models.tables.User.USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.UserRecord> getPrimaryKey() {
		return models.Keys.PK_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.UserRecord>>asList(models.Keys.PK_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.User as(java.lang.String alias) {
		return new models.tables.User(alias);
	}
}
