/**
 * This class is generated by jOOQ
 */
package models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentRecord extends org.jooq.impl.UpdatableRecordImpl<models.tables.records.CommentRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1890562657;

	/**
	 * Setter for <code>Comment.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Comment.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Comment.fileId</code>. 
	 */
	public void setFileid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Comment.fileId</code>. 
	 */
	public java.lang.Integer getFileid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Comment.userLogin</code>. 
	 */
	public void setUserlogin(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Comment.userLogin</code>. 
	 */
	public java.lang.String getUserlogin() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>Comment.date</code>. 
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Comment.date</code>. 
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>Comment.content</code>. 
	 */
	public void setContent(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Comment.content</code>. 
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return models.tables.Comment.COMMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return models.tables.Comment.COMMENT.FILEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return models.tables.Comment.COMMENT.USERLOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return models.tables.Comment.COMMENT.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return models.tables.Comment.COMMENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getFileid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserlogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContent();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CommentRecord
	 */
	public CommentRecord() {
		super(models.tables.Comment.COMMENT);
	}
}
