/**
 * This class is generated by jOOQ
 */
package models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends org.jooq.impl.UpdatableRecordImpl<models.tables.records.FileRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 619713660;

	/**
	 * Setter for <code>File.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>File.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>File.meetingUserId</code>. 
	 */
	public void setMeetinguserid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>File.meetingUserId</code>. 
	 */
	public java.lang.Integer getMeetinguserid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>File.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>File.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>File.sizeKb</code>. 
	 */
	public void setSizekb(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>File.sizeKb</code>. 
	 */
	public java.lang.Integer getSizekb() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>File.addedTime</code>. 
	 */
	public void setAddedtime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>File.addedTime</code>. 
	 */
	public java.sql.Timestamp getAddedtime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>File.hashMD5</code>. 
	 */
	public void setHashmd5(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>File.hashMD5</code>. 
	 */
	public java.lang.String getHashmd5() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return models.tables.File.FILE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return models.tables.File.FILE.MEETINGUSERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return models.tables.File.FILE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return models.tables.File.FILE.SIZEKB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return models.tables.File.FILE.ADDEDTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return models.tables.File.FILE.HASHMD5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMeetinguserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getSizekb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getAddedtime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getHashmd5();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FileRecord
	 */
	public FileRecord() {
		super(models.tables.File.FILE);
	}
}
